title: Macroball
remote_theme: pmarsceill/just-the-docs
aux_links:
  "Join Discord":
    - "//discord.gg/rVUMvee43f"
  "Interest Check":
    - "//forms.gle/C9Lr4JAAwGBj2WsL8"

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true